// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC2_dECI4RCz2juFuIOWRAzpBRI5doaHY',
    appId: '1:32487584001:web:8a9dda41e1e2bd3c0f2b00',
    messagingSenderId: '32487584001',
    projectId: 'fir-crud-b501f',
    authDomain: 'fir-crud-b501f.firebaseapp.com',
    storageBucket: 'fir-crud-b501f.appspot.com',
    measurementId: 'G-SF2EYY0MZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCpMWsdy3K0YQz0XewAM-AEv0_bB7xpfQ',
    appId: '1:32487584001:android:b9027379ee5358400f2b00',
    messagingSenderId: '32487584001',
    projectId: 'fir-crud-b501f',
    storageBucket: 'fir-crud-b501f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQrXHTjSxy3y0CD2eYXpUmgKPdf2qJidw',
    appId: '1:32487584001:ios:0e7d62fbc033fe470f2b00',
    messagingSenderId: '32487584001',
    projectId: 'fir-crud-b501f',
    storageBucket: 'fir-crud-b501f.appspot.com',
    iosClientId: '32487584001-3ukhcnseghdlnftu9ivrmila8t87mq5k.apps.googleusercontent.com',
    iosBundleId: 'com.flutterkage2k.firebase06092121',
  );
}
